### ISSUE TITLE
How should the message length be communicated?

### ISSUE THREAD

**Issue by timonegk** [NUbots/RobocupProtocol#2]
The length of the robocup.proto message is not fixed because there are `repeated` fields. Therefore, we need some way of determining how many bytes should read for a single message.
This encoding should be standardized so that there is a common solution for all teams. What do you currently do?
If there is no common solution yet, we propose to prefix each message with four bytes containing its length in the network byte order.

**Comment by Bidski** [comment]
Even with a TCP connection it is still possible for the device to end up out-of-sync in the message stream, and a simple 4-byte message length followed by the message provides no means for recovering synchronisation. We have been experiencing this issue with the webots controller recently, one unaccounted for byte leaves you trying to read in a 2.5GB message which inevitably fails to deserialise. 

I feel like more than just the message length prefix is needed to allow for the the possibility to recover synchronisation. To this end some more data in the header would be needed
```
"globally" unique message header
4 byte message length (N) in network byte order
N bytes of data
```

For the "globally" unique message header we like to use `0xE2 0x98 0xA24` (UTF-8 code for a radiation/hazard symbol) for other protobuf-concatenated message streams that we use and this seems to work well. So perhaps this might suffice? `0xE2 0x9A 0xBD`  (UTF-8 code for a soccer ball symbol) might be more appropriate given the context though.

**Comment by timonegk** [comment]
I see, ending up totally out of sync with the 4-byte message length was not a problem that we experienced yet. But if that's a problem for you, the globally unique message header would be a good way to solve the issue. And I definitely second the soccer ball symbol!

**Comment by TrentHouliston** [comment]
Use UDP for the communication protocol with one message per packet, problem solved as the size is encoded in the size of the packet already

**Comment by timonegk** [comment]
Okay. Then this is probably not necessary. `recv` still needs the package length, but something like 1024 should be sufficient for the message, I guess.

**Comment by TrentHouliston** [comment]
In UDP you don't use recv so much, just use recvmsg instead. Something like this
https://github.com/Fastcode/NUClear/blob/master/src/extension/network/NUClearNetwork.cpp#L415-L440

**Comment by timonegk** [comment]
Thank you very much for the help! I will close this issue now. See you at the RoboCup!
